// 'use client'
import './globals.css'
import Nav from '@/components/Nav'
import BaseProvider from '@/contexts/base-provider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <BaseProvider>
        <div className="min-h-screen">
          <Nav />
          {children}
        </div>
      </BaseProvider>
    </html>
  )
}
