"use client";
import "./globals.css";
import Nav from "@/components/Nav";
import { StyledEngineProvider } from "@mui/material";
import { SnackbarProvider } from "notistack";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
      <StyledEngineProvider injectFirst>
        <html lang="en">
          <body className="" id="_next">
          <SnackbarProvider maxSnack={3} anchorOrigin={{ vertical: 'top', horizontal: 'center' }}>
            <div className="min-h-screen">
              <Nav />
              {children}
            </div>
            </SnackbarProvider>
          </body>
        </html>
      </StyledEngineProvider>
    
  );
}
